### ISSUE TITLE
Disabled and hover states on square and icon buttons

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#145]
## Description

No cursor: pointer on disabled square buttons

Hover (with pressed state) on icon button

## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

**Comment by ezwelty** [comment]
Reopen with details if still relevant.
