### ISSUE TITLE
Fix mobile website for landscape orientation

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by ezwelty** [comment]
Is this a matter of making the location drawer full width (see screenshot below)? Or am I missing other issues with the landscape orientation view?

![image](https://user-images.githubusercontent.com/377523/209781199-db78513f-a1b9-478b-945f-081ae049a92d.png)
