### ISSUE TITLE
Border-radius on top bar does not align with input like in design

### ISSUE THREAD

**Issue by SirajChokshi** [falling-fruit/falling-fruit-web#197]
Visual error with top bar + search input

![image](https://user-images.githubusercontent.com/19193347/137441237-a4cd509e-2905-4b04-b712-524aeb6ad57a.png)
vs
https://www.figma.com/file/Ry8tCDzQmtpOAsKMOjuqGS/Falling-Fruit?node-id=1776%3A269

**Comment by ezwelty** [comment]
I can't identify the issue from comparing the designs and screenshot. Is the search button too far right?

**Comment by wbazant** [comment]
Not clear to me either!
