### ISSUE TITLE
Whole app accessibility

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#201]
**Describe the the feature request**

Nav should be more compact by having
less whitespace
smaller icons
slightly bigger text
This will be more usable too
See example navbars of apps on Android or iOS:
photo_2021-09-23_01-44-51
photo_2021-09-23_01-44-44
Compare to
image
text size is too small
icons too big
too much whitespace above icon and below text
Gray on navbar is too light (compare to gray in apps for iOS and Android) "not wcag compliant"
@SirajChokshi

**Comment by ezwelty** [comment]
@Qrtn Images are not showing up?
