### ISSUE TITLE
Production internationalization

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#204]
## Description

In order for our app to actually make it into production, the text in the app needs to support being translated.

We're currently using `react-i18next`, but there is a light-weight, easier to use solution available called LinguiJS. You can check out the documentation here: https://lingui.js.org/

We need to switch to LinguIJS. At the same time, the text in our app needs to be standardized (as much as possible) to what text was already on the old Falling Fruit website and has translations.

## Learning objectives

- PIcking up external libraries quickly
- Understanding how to internationalize an app
- Nuances, like pluralization, etc.
- Standard file formats that carry translations
- Learning Phrase app, the platform on which translators collaborate with developers

## Todo

- Understand how to use LinguiJS
- Understand the current approach for internationalization
  - https://github.com/hack4impact-uiuc/falling-fruit/pull/108
- Replace current react-i18next calls with LinguiJS
- Replace things like detecting locale, etc. with LinguiJS-specific plugin
- Standardize text in the app with translations that are already available on Phrase app

## Useful links

- https://lingui.js.org/
- https://lingui.js.org/tutorials/react.html
- https://phrase.com/blog/posts/localizing-javascript-react-apps-with-linguijs/
- Access to Phrase app workspace (need to ask Ethan to give to appropriate developer once assigned)

**Comment by Qrtn** [comment]
Ethan, thanks for pointing this out. We can choose to always set an explicit id, especially since Phrase already contains ids. We also don't necessarily need to include a default English translation in the code.

**Comment by wbazant** [comment]
Closing as the LinguiJS part is unplanned, and we're tracking the epic through the label https://github.com/falling-fruit/falling-fruit-web/labels/translation.
