### ISSUE TITLE
Sorting User Reviews Break Lightbox Order

### ISSUE THREAD

**Issue by SirajChokshi** [falling-fruit/falling-fruit-web#266]
**Describe the bug**
When a user is logged in their reviews are shown first on a location, but clicking the images results in an error because the lightbox does not know to preprend the current user's review images

**Expected behavior**
The lightbox is reordered to reflect the page changes

**Comment by ezwelty** [comment]
@SirajChokshi I would actually suggest that we simply sort reviews chronologically, whether someone is logged in or not.

**Comment by ezwelty** [comment]
To find a solution to #295, I dropped the sorting of user reviews up top. User reviews could be placed first if desired in the future by sorting reviews upstream of reviews, lightbox, and carousel creation.
