### ISSUE TITLE
Add page for password reset

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#303]
An entry point needs to be added for password reset. Currently, the password reset email links to the `api/user/password` endpoint directly, which results in a blank page with the error text {"error":"API key is missing"} since it is not meant to be used directly.

**Comment by Qrtn** [comment]
@ezwelty we have a page for setting the new password from the email. You can link to

`https://falling-fruit.vercel.app/password/set?token={token}`

in the password reset email.

**Comment by ezwelty** [comment]
@Qrtn Excellent, I have updated the test API. I also tested the flow and it seems to work as expected!
