### ISSUE TITLE
Allow user to suggest new type when adding a location

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#305]
When adding a location (or editing an existing location), the current website allows users to select existing types by selecting from search results in a dropdown list, or to create a new one by simply selecting their input (https://www.fallingfruit.org/locations/new):

![image](https://user-images.githubusercontent.com/377523/164996000-000681d0-ba23-4639-8372-2bd5fc2e723d.png)

Some version of this functionality needs to be implemented, using `POST api/types`. My thought was that we could present a form with common name(s) (passed as `common_names.en` by default?), scientific name(s) (`scientific_names`), and submission notes (`notes`). Once created, it would also be directly added to the types selector in the form. Crucially for performance, the new type should be added to the locally-stored types incrementally, without reloading all types again from `GET api/types`.

**Comment by ezwelty** [comment]
@wbazant Finally had a chance to try the draft of this feature in #419 . An exciting addition! Some bugs / quirks I notice:

* The initial input could be either a common name or a scientific name. So it needs to be possible to either convert the auto-filled common name to a scientific name, or add "Scientific" or "Latin" to the "Language" list and change "Common Name" to "Name". A common name is not required. All that should be required is a name (in any language). Right now, in addition to a common name, either scientific name must be added (and then optionally removed) or notes must be provided before the form can be submitted.
* The types in the Parent type dropdown should be formatted as they are elsewhere (bold common name, italic scientific name). Actually, could the dropdown from the "edit location" be reused?
* The Parent type dropdown does not list all types? e.g. Malus pumila 'Gala' was missing for me.
* The modal is very slow to open. The text inputs are extremely slow to the point of being unusable.
* It is clever to restrict Taxonomic rank to be less than the rank of the parent, but there is a bug when parent is subspecies (lowest rank), e.g. Acer pseudoplatanus 'Atropurpureum'. Then it shows "polyphyletic" (highest). It should show "subspecies". A safer logic would be to show ranks below or equal to parent rank, at least when parent is "polyphyletic", "multispecies", and "subspecies".
* Setting taxonomic rank should be possible without a parent type, since the parent may not exist. (e.g. adding a species in the absence of the genus).
* The format cannot be submitted unless notes It isn't immediately clear that notes are required. 

Stretch goals – mostly for me as they touch on the API and database:

* Provide a comprehensive list of languages (and maybe regions?) for the dropdown. Until the API can handle arbitrary language/region codes, the language information can be appended to the notes to at least aid admins in reviewing the type.
* Pass through the user_id of logged in user submitting the type (e.g. to be able to contact them for questions).

**Comment by wbazant** [comment]
Sure, those all make sense! Latin/Scientific as name does make the form simpler.

Notes shouldn't be required. Currently the form needs to be interacted with ('dirty') to be submitted in formik - but since we auto-populate it to an extent, it should probably start dirty.

I've removed lowest rank taxa from parent drop-down intentionally, but actually, you're right, we can have a parent on the same level as a child. I also thought the parent + taxonomic level choice should be coherent, but maybe they should be the other way round: first level then parent?

**Comment by ezwelty** [comment]
@wbazant Thinking about this some more, it might make sense to simplify the modal to just this:

```
[ language ] [ name ]
...
[ notes ]
```

If someone submits a scientific name, the taxonomic rank and parent taxon are implicitly provided. Conversely, if they don't know the scientific name (or unfamiliar with binomial nomenclature), then asking for taxonomic details is pointless. What we then need is names (maybe they know the plant under multiple names/languages) and/or notes (a description of the plant, link to wikipedia article, photo they find by searching the name in Google Image search, ....) that would help us understand what they mean.

A common ambiguity is users tagging locations as `mûrier`, which in French can mean either mulberry (_Morus sp._) or blackbery (_Rubus sp._). These plants are nothing alike, but without any additional information, there isn't any way to know.

**Comment by wbazant** [comment]
Sure, changed it to just a list of language / name pairs + notes:
![Screenshot from 2024-08-26 12-32-10](https://github.com/user-attachments/assets/3fb1fbab-1891-4b76-8ef8-9d7ccca013a2)

**Comment by wbazant** [comment]
Not going to add pointless types to the site now, but the form is there.
