### ISSUE TITLE
Add support for editing the position of an existing location

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#306]
A feature of the current website that is not yet supported is the ability to change the map position of an existing location.

**Comment by wbazant** [comment]
On desktop, I suggest extending the current UX by making the map movable, as when during adding a new location. Other locations should be visible (like in #393) but not the old position of the location being edited.

On mobile, I suggest extending the current UX by prepending a step, just like adding a new location has two steps. When editing, the user will first confirm the position of the existing location or move the marker, mock-up:
![Screenshot from 2024-06-06 22-52-03](https://github.com/falling-fruit/falling-fruit-web/assets/16976512/690f15ff-4523-4913-bedb-caeee767210c)
. The back button in the second step of "edit location" should go to the first step, not back to the map.

As an aside, do we want to make the title of the second step "New location details" and "Edit location details"?

**Comment by ezwelty** [comment]
@wbazant Following the same flow as when adding a location is probably the best place to start. (Though I wonder whether forcing two steps will feel too cumbersome, and better thus to link to edit-location-position from the main edit-location form).

Do you think the mobile view should also include two markers, one for old and one for new position?

Regarding naming, my preference is always to use text that already exists on the website or mobile apps, since we have translations for these, or at least as simple as possible so that translations are easier. So e.g. "Add location", "Edit location" from https://github.com/falling-fruit/falling-fruit-mobile/blob/main/www/locales/en.json.

**Comment by wbazant** [comment]
> Do you think the mobile view should also include two markers, one for old and one for new position?
Yes, I think it'd be nice if the same edit location component worked on both desktop and mobile for editing the location!

**Comment by wbazant** [comment]
This is now working (moving the marker on desktop, and screen on mobile)
