### ISSUE TITLE
Button to edit a location is not visible [desktop]

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#309]
The button to edit a location is not visible in the desktop view, although it is visible in the mobile view.

For example: http://localhost:3000/entry/3471

On mobile:
![image](https://user-images.githubusercontent.com/377523/169322779-32e8abb0-43c7-4d60-a1e8-591059134781.png)

On desktop:
![image](https://user-images.githubusercontent.com/377523/169322969-44301c07-155e-4938-81a7-a1b1ae40ba6f.png)

**Comment by Qrtn** [comment]
@ezwelty how did you get to that point on desktop? Normally there's an edit button here:

![image](https://user-images.githubusercontent.com/4369024/206875380-096b9557-f790-40e3-959a-f2a0c22d63ae.png)

**Comment by Qrtn** [comment]
@ezwelty actually it seems like the edit button doesn't show when not logged in.

**Comment by Qrtn** [comment]
FF allows anonymous editing, so I fixed the edit button to always show
