### ISSUE TITLE
Make parent types with themselves as their only child not expandable

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#311]
Under each parent type, the type filter lists the type associated with that parent as well as any children types. Often, when the tree is showing limited results (e.g. "Only on map"), many parent types are shown with themselves as their only child. For example, in the screenshot below, _Juglans regia_ is the only child of _Juglans regia_. In these cases, the parent does not need to be expandable and could stand in for its associated type. However, it is not clear then if (de)selecting a parent should select/deselect the parent and all of its children (the current behavior) or the parent and only the children currently shown.

![image](https://user-images.githubusercontent.com/377523/169836999-c87900ee-5eb1-4913-91a3-868f776333a0.png)

**Comment by wbazant** [comment]
I think this can be implemented through the behaviour of culling parents of single children in the tree, for example here, "Wild garlic" being under "Onion" was confusing. 

<img width="689" alt="Screen Shot 2024-05-23 at 13 41 29" src="https://github.com/falling-fruit/falling-fruit-web/assets/16976512/15a98e45-78cb-45c1-bcf5-42bed3469ee0">
