### ISSUE TITLE
Mobile list is empty if loaded directly from URL

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#347]
Going to the list directly from a URL results in an empty list. For example: `/list/@40.0405402577959,-105.2632395613161,21z`. Locations are not loaded. Only when switching to map view are the locations loaded.

![image](https://user-images.githubusercontent.com/377523/212370572-dbec2287-5afe-4d90-9cd3-c05c7a3a339c.png)

**Comment by wbazant** [comment]
This happens because the `view` object is null when src/redux/selectParams.js is called after loading the empty page, and the error is silenced because `src/redux/listSlice.js` there is no handler for `fetchListLocations.rejected`. A very nice bug!

**Comment by wbazant** [comment]
Proposed resolution is to require a loaded map - if the /list/ URL is accessed first, briefly visit /map and then come back to /list.

**Comment by ezwelty** [comment]
From https://github.com/falling-fruit/falling-fruit-web/pull/419#issuecomment-2284862604

> This seems to be broken in a new way. http://localhost:3000/list/@40.0405403,-105.2632396,21z loads the list, but switching to the map view does not load markers (weirdly I only see one basemap tile loaded, the rest load only after the map is moved), and moving the map does not update the map center and zoom in the URL, such that clicking back to the list always shows the original list.

**Comment by wbazant** [comment]
This is now fixed (I visited https://beta.fallingfruit.org/list/@40.0405402577959,-105.2632395613161,21z and got locations back)
