### ISSUE TITLE
Disable location button when permission is denied

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#351]
The location tracking button is displayed normally even when location permission has been denied:

![image](https://user-images.githubusercontent.com/377523/216561067-b23a2a46-5243-47bc-813d-dce388e13c3f.png)

Once clicked, the location button switches to an X icon:

![image](https://user-images.githubusercontent.com/377523/216560628-34639c3a-749f-407c-9b51-7f5ce8026d6c.png)

Ideally, it would show as a greyed-out version of the original instead.

**Comment by wbazant** [comment]
This is current styling:
```
.hutGOq:enabled {
  cursor: pointer;
}
```
This CSS looks nice:
```
.bGLhd:enabled {
  cursor: not-allowed;
  opacity: 0.5;
}
```
