### ISSUE TITLE
Add OpenStreetMap map layer

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#352]
Many users prefer OpenStreetMap as a basemap because it is much more detailed than Google Maps in some regions. See https://github.com/falling-fruit/falling-fruit/blob/master/app/assets/javascripts/mapcommon.js#L134 for implementation details.

**Comment by halziebol11** [comment]
I'm thinking this is a more complicated issue than a first due to the way the google-map-react package works. There is no easy substitution available for the base layer.

**Comment by ezwelty** [comment]
@halziebol11 Thanks for weighing in. The limitations of `google-map-react` have also come up in the context of (poor) performance – see #142. We already have a lot of logic written with the Google Maps Javascript API for the current website and mobile app, which makes we wonder whether dropping `google-map-react` in favor of using the Google Maps Javascript API directly (and so writing our own React wrappers) would be worth it in the long run.
