### ISSUE TITLE
Allow logged-in users to select default language

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#354]
Add a dropdown select in the user account panel allowing users to choose the default language to use when they are logged in to the website and their is no locale specified in the url.

**Comment by joaodantas91** [comment]
@ezwelty I would like to work on this, can you assign to me?

**Comment by joaodantas91** [comment]
@ezwelty  I would like to work on this, can you assign to me?

**Comment by ezwelty** [comment]
@joaodantas91 Sorry for the delay. There's been a flurry of activity on the repo this month (which is fantastic) and I missed your comment.

This is a very old issue that was originally targeting the old website. The beta site (this repo) now both detects user language and caches user language selection, so I'm not sure whether it is still needed. I'm going to close for now and encourage you to look at some of the related issues, e.g. #489 , #488.
