### ISSUE TITLE
Help obtaining an Falling Fruit Backend API key for falling-fruit-web local setup

### ISSUE THREAD

**Issue by billykeyss** [falling-fruit/falling-fruit-web#355]
I am looking to setup the falling-fruit-web locally on my machine. In the setup instructions, it is required to add in a falling fruit API key into the .env file. How can we obtain a API key for [Falling Fruit backend](https://github.com/falling-fruit/api) in order to run/develop the web app locally?

I tried interacting with the API on both Swagger and Curl but was not able to make successfully make the calls

```
➜  ~ curl -X 'GET' \
  'https://fallingfruit.org/test-api/0.3/locations?bounds=-5,-180|5,180&center=1.359,103.807&muni=true&invasive=false&limit=1000&offset=0&photo=false&count=false' \
  -H 'accept: application/json'
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>503 Service Not Available</title>
</head>
<body>
<h1>503 Service Not Available</h1>
</body>
</html>
```

**Comment by ezwelty** [comment]
@billykeyss Thanks for your interest! I made things easier and simply shared an API key (along with additional details about the different environment variables). See the updated `example.env` and developer documentation in [`/docs`](https://github.com/falling-fruit/falling-fruit-web/tree/main/docs).

Note also that https://fallingfruit.org/test-api/0.3 is no more. Either use the production API at https://fallingfruit.org/api/0.3 or run it locally (see [falling-fruit/falling-fruit-api](https://github.com/falling-fruit/falling-fruit-api)) with a local database (see [falling-fruit/falling-fruit](https://github.com/falling-fruit/falling-fruit)).

**Comment by ezwelty** [comment]
@billykeyss I hope my changes addressed your issue? Closing this but feel free to reopen or create a new issue as needed.
