### ISSUE TITLE
Location always reopens as map version from Google Street View

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#360]
Closing Google Street View opened from list-location opens map-location rather than list-location. This is because opening Street View redirects first to map-location. Could this be fixed by using a separate Google Map component for Street View? Or by some other way displaying Google Street View without the need to switch to the map first?

**Comment by wbazant** [comment]
This is now working as proposed (you get the list flavour of location when closing the street view)
