### ISSUE TITLE
Revisit location drawer

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#364]
The location drawer is one of the most complex and fragile parts of the code and may be worth redesigning with a goal of simplifying the layout and underlying logic. For example:

- Move photos to within the drawer (below location types)
- Use a common fullscreen layout for map and list view that allows scrolling (e.g. https://jsfiddle.net/ofg89bna/1/)
- Only display location types when drawer is in middle position (avoiding an extra API call), then clicking an expand button for a full view

**Comment by wbazant** [comment]
I also think - although not super sure about this - we should not offer the reviews tab when there are no reviews.

I tried to grey out the reviews tab. It's not that good - there's a bit of futility to showing the tab - but it's under commit d76c0752aad67eb8598b9dbb42853d014c887283 that I then reverted. The next commit e7a94d824096d3a6e4e62bfe3ac044001fb9d333 takes them out, and it feels quite natural to me, but also I've opened that drawer many times now so I don't really know any more.

**Comment by wbazant** [comment]
Worth adding a comment that I wrote an implementation of the drawer that replaced the cupertino-pane import, since at some point it was giving me an annoying flicker and I thought I can make a nicer drawer. So the animations etc. might be a bit different. Also, the drag handle is different - the AI made me a semi-transparent one and I liked it enough to keep it.

**Comment by wbazant** [comment]
@ezwelty the drawer changed the code but also the layout a bit, would you check it out and close this issue if you think it's in good shape?

**Comment by ezwelty** [comment]
@wbazant Thanks! I think things are in fine shape, and if I feel strongly enough about something in the future, I'll bring it up in a new and more fleshed out issue or PR.
