### ISSUE TITLE
Add newsletter unsubscribe endpoint

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#366]
To be consistent with modern laws and best practices, we should provide an endpoint with which users can unsubscribe from a newsletter directly from a link in said newsletter.

**Comment by ezwelty** [comment]
It may be easier to use Postmark's unsubscribe process. See https://postmarkapp.com/developer/webhooks/subscription-change-webhook and https://postmarkapp.com/support/article/1208-how-to-add-an-unsubscribe-link.

**Comment by wbazant** [comment]
I saw an unsubscribe link in the newsletter, I think this is done now!
