### ISSUE TITLE
When search matches parent type, information about children is not shown

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#373]
I think this is a bug, spotted when messing with the search filter.

When I type "animal" into the text box I should still see "Fish" and "Crayfish", arguably.
![Screenshot from 2024-05-22 20-55-30](https://github.com/falling-fruit/falling-fruit-web/assets/16976512/1df71c40-9ec3-4a72-bea5-73a05bdd41b2)
![Screenshot from 2024-05-22 20-55-04](https://github.com/falling-fruit/falling-fruit-web/assets/16976512/cc457902-140b-4d09-be7b-33f515ca9a15)

**Comment by ezwelty** [comment]
@wbazant Agreed!
