### ISSUE TITLE
Searching in the list view sometimes doesn't update locations on list

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#389]
Searching in the list view doesn't currently update the list. Related to #347, and possibly related to #387 through the theme of missing bounds.

For reproduction, try switching between e.g. Parliament Square and Shoreditch in London:

1. Start from the first place
http://beta.fallingfruit.org/map/@51.5006791699648,-0.12691335000002368,16z
2. Transition to list view and check the locations (here, an apple tree and a dumpster)
3. Search for the other place - URL changes but the list is not updated
4. Transition to map
5. Transition back to list - only now get the updated list

An additional error is shown in dev mode, which hints at problems with bounds setting:
![Screenshot from 2024-05-29 20-33-20](https://github.com/falling-fruit/falling-fruit-web/assets/16976512/604bb5a5-3091-4ecb-a9e4-19b14e023763)
Shoreditch triggers the error because of its size (searching for New York produces a view that was sufficiently zoomed out)

**Comment by wbazant** [comment]
The data flow is correct in the #419 PR, but we never get any locations, because this reducer:

```
    [selectPlace]: (state, action) => {                                                        
      const { ne, sw } = action.payload.place.viewport                                         
      const maps = state.getGoogleMaps()                                                       
      const bounds = new maps.LatLngBounds(                                                    
        { lat: sw.lat, lng: sw.lng },                                                          
        { lat: ne.lat, lng: ne.lng },                                                          
      )
      state.googleMap.fitBounds(bounds)
    }, 
```
reliably zooms out far into the cluster view. Changing it into `state.googleMap.panToBounds(bounds)` returns no locations, and putting a console.log in src/redux/selectParams.js shows why: the map realises it is not being rendered, and sets its size to 0x0.

Two solutions I can think of right now are:
- redesign the list page so it doesn't let you search
- repeat the workaround with going to the map and then back

**Comment by wbazant** [comment]
This failed QA (searching for Shoreditch led me to a zoomed out view), and also I got hit with the #443 bug while QAing.

**Comment by wbazant** [comment]
I had another go at this, and I think the fundamental issue here is, translating URLs like `/list/@51.5244057,-0.0795032,14z` into a list of locations requires bounds that come from a viewport, but the map doesn't tell you what its bounds are when it's not on the screen. I've been putting workarounds in:
 - if the URL is refreshed, go to the map and then back to the list, to make sure the data is populated
 - store the view in Redux for when the map doesn't tell you what its bounds are (state.viewport)

I've just tried to use state.viewport to figure out the right zoom for the place, with "how big the map would have been if it was on the screen, and then fitted the bounds for the place bounds" kind of logic, but really, the list URL should just contain the bounds. Then the place search can go to /list/newBounds, and going between map and list can convert between URL types when the map goes in and out of view. This is a big design change for the app - maybe not a huge code change, but it's an introduction of a new idea for sure - so I'll think about it more, but I feel I'm at the start of working something out here.

**Comment by ezwelty** [comment]
@wbazant I don't think that the URL can contain map bounds, because that is fundamentally tied to a screen size and aspect. For example, sharing the URL between devices or flipping the device from portrait to landscape would make the bounds no longer match the map. Flipping between map and list view is a very common feature request for the mobile app, so I'm motivated to keep map and list more in-sync, so that we can in the future e.g. add show-on-map buttons directly in the list, have the list appear as a drawer over the map, etc.

If the map div size is known, then the map bounds can be directly calculated from the center and zoom we have from the URL (e.g. https://stackoverflow.com/questions/3774579/calculate-bounds-from-center-and-zoom-google-maps-api-v3). Would that be a solution?

**Comment by wbazant** [comment]
I'll work on this more, but you're right that it's doable. Given place bounds from the search, we can take center as the middle of the search, and find the smallest zoom level fits the place bounds by using these inputs:
- the place bounds
- the Mercator projection formula
- tile size (256 x 256 px)
- viewport size (variable in pixels)
 
Then we can calculate the slightly bigger map bounds.

I got this snippet for a zoom calculation, not tested yet:
```
var WORLD_DIM = { height: 256, width: 256 }; // tile size
var ZOOM_MAX = 21; // max zoom level in Google Maps

function latRad(lat) {
  var sin = Math.sin(lat * Math.PI / 180);
  var radX2 = Math.log((1 + sin) / (1 - sin)) / 2;
  return Math.max(Math.min(radX2, Math.PI), -Math.PI) / 2;
}

function getZoom(bounds, mapDim) {
  var ne = bounds.getNorthEast();
  var sw = bounds.getSouthWest();

  var latFraction = (latRad(ne.lat()) - latRad(sw.lat())) / Math.PI;

  var lngDiff = ne.lng() - sw.lng();
  var lngFraction = ((lngDiff < 0) ? (lngDiff + 360) : lngDiff) / 360;

  var latZoom = Math.floor(Math.log(mapDim.height / WORLD_DIM.height / latFraction) / Math.LN2);
  var lngZoom = Math.floor(Math.log(mapDim.width / WORLD_DIM.width / lngFraction) / Math.LN2);

  return Math.min(latZoom, lngZoom, ZOOM_MAX);
}
```
https://chatgpt.com/share/67079d84-8570-8006-8802-87961f1eb95d

**Comment by ezwelty** [comment]
@wbazant I think the situation is a bit simpler than this. To call `/locations`, the list needs `types`, `muni`, `invasive`, `bounds`, and `center`. This endpoint does not use a `zoom` parameter (see https://petstore.swagger.io/?url=https://fallingfruit.org/api/0.3/openapi.yml#/Locations/get_locations). I notice that it is included in the API calls made by list and map, and should be removed. (Shame on me for not yet making the API more strict)

1. Searching for a place returns `geometry.viewport`. The effective map `bounds` can be calculated by converting this result to Web Mercator, adding padding to match aspect ratio of the map container, and converting back to WGS84 (see conversions in `clusterBounds`). `center` is the center of the Web Mercator bounds, converted to WGS84.
2. Loading the list for the first time (so with a map `center` and `zoom`, but no map rendered), then function I linked to earlier should help. Basically the `zoom` specifies the scaling to pixels, the map container the pixels, and the `center`, converted to Web Mercator, the center of the final bounds (which then are converted back to WGS84).

Alternatively, if the list were rendered above the map (in the sense that the location drawer is above the map), would that make the map available to do these calculations for us?

**Comment by wbazant** [comment]
>      Alternatively, if the list were rendered above the map (in the sense that the location drawer is above the map), would that make the map available to do these calculations for us?

I think that's potentially a very good idea if the list doesn't make sense as a stand-alone offering, and there are some other related views that we don't have a place for - see #502

**Comment by wbazant** [comment]
I've been thinking about making the list view read-only. A super rough mock-up:

![Screenshot from 2024-10-14 09-56-52](https://github.com/user-attachments/assets/98e67469-47b8-445b-b558-12921fd55b94)

The coordinates would more usefully be a place description, retrieved through reverse geocoding - or instead we could maybe show the size of the selected slice in kilometers / miles.

The sorting toggle would explain what the '15 meters' is under the location, and we could (later) also offer another ordering - last edit date - which would help the user see recent activity related to their favourite place as part of #506.
