### ISSUE TITLE
toast the error on failed search

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#392]
I've had the dubious honor of triggering the API ofer quota today. I use a different key for localhost dev but was playtesting a beta site on another laptop. I was looking into the search behaviour, but hopefully didn't completely deplete it, I used it maybe like 10 times in total.

Anyway, the error about being overquota is not toasted on the beta site, and I had to check console.log to find out.

<img width="496" alt="Screen Shot 2024-06-05 at 22 43 06" src="https://github.com/falling-fruit/falling-fruit-web/assets/16976512/a099cb8c-6698-45df-b44b-97219601df94">
<img width="1437" alt="Screen Shot 2024-06-05 at 22 43 20" src="https://github.com/falling-fruit/falling-fruit-web/assets/16976512/a51df45c-371a-4905-b704-8ff77305cca4">

**Comment by ezwelty** [comment]
@wbazant Nope, this is definitely my fault. I'm geocoding a large tree inventory for eventual display on the sit, and hit the daily limit set on the Falling Fruit account (30,000). Extremely unlikely to ever happen under normal conditions.

**Comment by ezwelty** [comment]
Closing this for now as "fixed" in the sense that I will be better about monitoring and managing API quota limits. The limit could be removed, but this would expose us to the potential of heavy use by a nefarious 3rd party and a correspondingly large bill from Google.
