### ISSUE TITLE
Regression: Cannot move map when location drawer is open

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#399]
A recently introduced bug prevents the map from being pannable or zoomable when the mobile location drawer is half open.

**Comment by wbazant** [comment]
Thanks for spotting! I checked a few commits and the bug first appears in 37bdd035d111eebd1ad04b6cd9506c2a011f3f49, pull request #391. The layout with the always-open map still seems like a good idea if this can be fixed, but I'm not sure how right now.
