### ISSUE TITLE
(desktop) marker behaviour when clicking a few locations in succession

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#412]
Low importance, but the behaviour changes as part of #406  so adding the issue to track the change.

When clicking a few locations quickly, there's a race condition between setting the location. Say we initiate clicks of location X then Y and then receive callbacks for both, then among events timed as [X.pending, Y.pending, X.fulfilled, Y.fulfilled ] we can have a few different behaviours. 

The current implementation changes marker location for {X.pending, Y.pending} and populates location side pane however {X.fulfilled, Y.fulfilled} arrive, which is usually fine, but the naive Redux implementation sometimes looked buggy.

The proposed resolution is to not show the marker just after the click - only after the location loads - and to only accept fulfilled events corresponding to latest pending event. So, if  [X.pending, Y.pending, X.fulfilled, Y.fulfilled ], we'll show the spinner since X.pending, and place marker + side pane content on Y.fulfilled.

Showing the marker after the click too is possible and actually many other async implementations, I just had to pick something.

**Comment by ezwelty** [comment]
@wbazant Hmm, I would hardly qualify this as a bug, but I see what you mean after playing with this using a throttled connection. I agree with your proposed resolution, but do wonder whether it will be confusing for the marker not to appear on *.pending (if the location is slow to load, it might look like nothing happened). So showing the marker on *.pending but only showing the location once the latest pending is fulfilled is I suspect the best way to go.

**Comment by wbazant** [comment]
I agree with you! I've come to realize 
> The proposed resolution is to not show the marker just after the click 
was not very good, it made the UI feel laggy.
