### ISSUE TITLE
Mobile search header shown on pages where it should be hidden

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#414]
The search header is shown on pages where it shouldn't be, and as a result, it covers the "<- Back" button and some content at the top of the page.

* `/data` (but not `/about`)
* `/sharing`
* `/press`
* `/imports/:id`

<img src="https://github.com/falling-fruit/falling-fruit-web/assets/377523/8da6adf2-c96d-434a-872b-44fa2fda27af" width="300px">

**Comment by wbazant** [comment]
This is now fixed on the live site.
