### ISSUE TITLE
Add/edit review still using deprecated 2-step form

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#415]
Although on mobile "add location" is a single form (that combines location and review properties), "add/edit review" still uses a 2-step form (which, as a bug, is not scrollable on small screens). It should be replaced with the review section of the form used in "add location".

Add review
<img src="https://github.com/falling-fruit/falling-fruit-web/assets/377523/6e834848-56a8-4947-8d00-3d0a79fb3b98" width="300px"/>

Add location
<img src="https://github.com/falling-fruit/falling-fruit-web/assets/377523/e5853935-4881-4136-afd5-acb1ed740925" width="300px"/>

**Comment by wbazant** [comment]
I'm touching the review code so I might fix this issue- `src/components/mobile/MobileLayout.js` has "<EditReviewForm stepped ..." and I think just removing the argument and tidying up will do it.
