### ISSUE TITLE
(desktop) when back from location street view, street view should close

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#427]
I claim it's a small bug on the beta site.

To reproduce:
- be at location page on desktop like https://beta.fallingfruit.org/locations/1989910/@55.83459087460341,-4.252853449999975,14z
- press 'back'
- location should close

In my localhost the bug is worse -  pressing 'back' changes the location to the default location while keeping street view, so I'm filing an issue to not forget fixing this.

**Comment by ezwelty** [comment]
@wbazant I believe this will be closed by #419 ?

**Comment by wbazant** [comment]
This is now fixed on the beta site.
