### ISSUE TITLE
toast when there's no panorama available for a location

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#428]
Randomly found an example: https://beta.fallingfruit.org/locations/1756237/@32.331724099999974,-64.73249530000001,14z

Nothing happens on beta site but my refactored version on localhost logs this error:

Street View data not found for this location. MapsRequestError: STREETVIEW_GET_PANORAMA: ZERO_RESULTS: There are no panoramas found that match the search criteria.

We should toast it.

**Comment by ezwelty** [comment]
@wbazant I believe this will be closed by #419 ?

**Comment by wbazant** [comment]
This is live and working as proposed.
