### ISSUE TITLE
Show a location's multiple plants in mobile list and map labels

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#429]
I've added a second plant for one of the locations, and it's not being shown.

![Screenshot from 2024-07-20 17-13-36](https://github.com/user-attachments/assets/c0973866-a068-4993-a715-0779d040ef6d)
![Screenshot from 2024-07-20 17-13-27](https://github.com/user-attachments/assets/6654de95-5e55-4659-9017-1e82b9c26d65)

Proposal: if there are more plants at a location, list them next to a photo, allowing up to three lines. For 1,2,3 types list them, for 4+ list first three and say "+ {n - 3} more types (n total)"

**Comment by wbazant** [comment]
Not sure of the solution right now, but there is also an issue of filters being applied. Right now we just render the first plant for each location, but a match is an OR, so we might e.g. search for all apple trees in the area and see a strawberry, if there's a match to a location like 1809886. Maybe the verbiage should say  "+ {n - 3} more types matching filters"

**Comment by ezwelty** [comment]
Multiple types are now displayed in mobile list and map labels. Work on the types on the location page continues at #530.
