### ISSUE TITLE
Self (parent) not first position in type tree children

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#438]
The self checkbox for the parent type does not appear as the first child.

For example, "Freegan" should be the first in the list of children under "Freegan" parent:
![image](https://github.com/user-attachments/assets/24988948-fa03-4aea-852a-03aed5681453)

I believe this used to be the case, but not sure what introduced this regression.

**Comment by wbazant** [comment]
This is now fixed. @ezwelty you made the issue so I can't close it, but I think you can close this one too!
