### ISSUE TITLE
Wait to update map while sidebar width is adjusted

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#443]
While the sidebar width is adjusted by clicking and dragging, API calls (either `clusters` or `locations` and `types/counts`) are fired off continuously in quick succession. Updating the map should wait until the click is released.

**Comment by wbazant** [comment]
Additional requirement about map actions on resize: make sure there's no way for them to go to the default view. Just happened to me on mobile when a keyboard disappeared, and it was very distracting (I lost my place in the map).
