### ISSUE TITLE
double counted location

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#447]
why two grapes here? https://beta.fallingfruit.org/map/@55.8242027,-4.275226400000008,21z

**Comment by wbazant** [comment]
This one might be down to a poorly behaved user who was adding stuff through the current mobile app, and pressed 'submit' once too many, possibly due to bad internet.

**Comment by ezwelty** [comment]
@wbazant Because there were two locations at exactly the same position. I reported the second as a duplicate and then deleted it. Closing this but perhaps in some distant future the API could do something fancy to try to prevent this.
