### ISSUE TITLE
Misaligned type tree entries in Safari

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#461]
On my system (Mac OS 11.7.7), Safari (16.5) fails to correctly display the type tree. Chrome and Firefox do so correctly. The CSS styling should be revised slightly and tested on many browsers to confirm that it is displayed properly.

<img src="https://github.com/user-attachments/assets/8eab9309-57c7-4d71-9512-777d51c404b0" width="300px"/>

**Comment by arvin-z** [comment]
Hi @ezwelty 

I can work on this issue.
