### ISSUE TITLE
Calling locations API with `center` impacts performance and user experience

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#466]
Somewhere in #419 must have been a switch to globally calling the API `/locations` with the `center` param. I suspected this was to share data between map and list, but since the list also needs a photo, this isn't actually the case. So I suspect this was not intentional @wbazant?

The trouble with `center` for the map is that it is much more work for the database (which has to return the X locations nearest a position) and results in a strange experience in places with more locations than the limit. The difference is striking:

<img src="https://github.com/user-attachments/assets/bbac37ec-7b80-4f29-80b8-56b2b04ca8e2" width="300px">
<img src="https://github.com/user-attachments/assets/8aebecf1-4081-43a0-887d-51f9fcf08bba" width="300px">
https://beta.fallingfruit.org/map/@39.7375473,-104.9720279,16z

Related to #378.

**Comment by wbazant** [comment]
No, that was accidental! I think I rewrote `src/redux/selectParams.js` and passed the whole `bounds` objects in. The fix for this one is to only provide `center` in the call to selectParams that goes to the photo, and modify selectParams to only convertCenter if there was one provided.
