### ISSUE TITLE
Bad flow around images on about page with narrow screen

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#471]
The about page (https://beta.fallingfruit.org/about) does not render well on narrow screens. Photos that are placed alongside text squash the text into a very narrow strip. The proposal is that below a threshold screen width, these photos should be moved to above their text so that the text can use the full page width.

<img src="https://github.com/user-attachments/assets/9d095014-314b-484d-8656-8ecfcfda0e23" width="300px">
<img src="https://github.com/user-attachments/assets/2e1bab4b-2479-4c82-a592-3fc215ebd603" width="300px">

**Comment by marceloams** [comment]
Hi, could you please assign this issue to me? I'd like to work on it.

**Comment by ezwelty** [comment]
@marceloams Welcome and thanks for your interest. I've assigned you this issue.
