### ISSUE TITLE
Indicate whether user is logged in

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#472]
On desktop, logged in is indicated by the Sign in / Sign up buttons being replaced by a head-and-shoulders icon alongside user name or (if anonymous) account email:

<img src="https://github.com/user-attachments/assets/0333acd9-11fe-4597-a6dc-57664b7c6f3f" width="200px">

On mobile, there is no indication whether user is (still) logged in. This should be addressed. Given the current design, my suggested fix would be to set the text and icon color for "Account" to orange when user is logged in, but to only show the orange selection border when "Account" is actually selected.

Alternatively, we could potentially show head-and-shoulders icon alongside user name or email, as on desktop, but I fear that there would often not be enough space on mobile.

<img src="https://github.com/user-attachments/assets/5c4b870e-ad7e-4777-ade6-62b9ece3a49d" width="300px">

**Comment by ezwelty** [comment]
@vsnikhilvs Welcome! Thank you for offering to help out. I've assigned you this issue.

**Comment by vsnikhilvs** [comment]
> @vsnikhilvs Welcome! Thank you for offering to help out. I've assigned you this issue.

Hey @ezwelty , While trying to install deps, I am facing conflicts with react's version.

**Comment by ezwelty** [comment]
@vsnikhilvs I updated the lockfile in a recent commit. Perhaps this fixes your issue? If not, could you please elaborate, ideally by opening a new issue?

**Comment by vsnikhilvs** [comment]
Yea its fine

**Comment by wbazant** [comment]
Different proposed resolution: change the icon and text when the user is not logged in to

![Screenshot from 2024-10-29 08-56-49](https://github.com/user-attachments/assets/c50843f5-b442-4e29-87a5-aef5463b3d6b)
