### ISSUE TITLE
Remove "by Anonymous" in anonymous reviews

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#474]
Reviews without an `author` are currently displayed as "Reviewed on {date} by Anonymous". This should be removed, so that the string reads "Reviewed on {date}".

<img src="https://github.com/user-attachments/assets/5f1c0e6b-9579-4226-8f56-58a367b16c9a" width="300px">

https://beta.fallingfruit.org/locations/1824032

See `src/components/entry/Review.js`.

**Comment by IvySaskia** [comment]
Hello I came from hacktoberfest discord. I would like contribute on this issue.

**Comment by ezwelty** [comment]
@IvySaskia Welcome! Thank you for your interest in our project. I've assigned you this issue.

**Comment by joaodantas91** [comment]
#485
