### ISSUE TITLE
Internationalize the About page

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#492]
To display the About page in various languages, we need to move the text out of HTML and into the locale file, and use the same keys as on the live site.

Here's the live site with i18n_viz switched on:
https://fallingfruit.org/about?c=forager%2Cfreegan&locale=en&i18n_viz=1

See #488 and especially Ethan's guidance for translations at https://github.com/falling-fruit/falling-fruit-web/issues/488#issuecomment-2400821863

**Comment by manuelpastorringuelet** [comment]
Hey @wbazant, I can help with this issue. Could you please assign me? Happy to help.

**Comment by ezwelty** [comment]
@manuelpastorringuelet Welcome and thanks for offering to help. I've assigned you the issue.
