### ISSUE TITLE
Outdated Twitter Icon (Bird Logo) Still Displayed After Rebranding to "X"

### ISSUE THREAD

**Issue by mohit-1710** [falling-fruit/falling-fruit-web#495]
### Outdated Twitter Icon (Bird Logo) Still Displayed After Rebranding to "X"

**Issue Description:**
On the website, the Twitter icon is still showing the old bird logo instead of the updated X logo. 

### Steps to Reproduce

**Steps to Reproduce:**

1. Navigate to the [beta.fallingfruit.org](https://beta.fallingfruit.org/)
3. Observe the Twitter icon.

### Screenshots

![image](https://github.com/user-attachments/assets/8eb5140f-0457-4816-881e-f8f6045647be)

**Comment by mohit-1710** [comment]
@ezwelty please assign this issue to me .

**Comment by ezwelty** [comment]
@mohit-1710 Done! Also please update the URL to https://x.com/Falling_Fruit

I'll miss the bird though 😢

**Comment by wbazant** [comment]
Hi @mohit-1710 , would you like to stay assigned to this issue? If you still want to solve it but are stuck on something, feel free to describe the problem and I'll try to unblock you. If you're not working on it any more but made partial progress, you can also update the issue with notes and someone solving it might find it helpful.

**Comment by ahmedhalac** [comment]
@wbazant. Can you assign me on this too?

**Comment by ahmedhalac** [comment]
Quick question: Since I can't find X icon in @styled-icons/boxicons, is using an svg good idea?

**Comment by wbazant** [comment]
Yeah, that works! I found a boxicons thread about it: https://github.com/atisawd/boxicons/pull/921#issuecomment-2424830533 and a person there made a proposal, check out that one too?
