### ISSUE TITLE
Make Fruiting status dropdown not searchable

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#499]
The fruiting status dropdown is searchable, despite only having three options. On mobile, this is especially annoying because it triggers the opening of the keyboard.

Proposal: Make the dropdown behave the same as the location access or seasonality start and end month dropdowns.

**Comment by marceloams** [comment]
Hi @ezwelty, could you please assign this issue to me? I'd like to contribute and work on it.
