### ISSUE TITLE
Make "Add location" button more prominent

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#511]
Somewhere along the way, the "Add location" button lost the typical styling of orange buttons in the app and became very discrete. Even when enabled, it is hard to spot:

<img src="https://github.com/user-attachments/assets/8ff1771e-b577-4007-a1b8-69c5b8980fba" width="300px">
<img src="https://github.com/user-attachments/assets/86d5cb4e-6c1c-49c8-b34e-1d655d08ff17" width="300px">

It should be styled in the same way as the Sign up, Review, Submit, ... buttons.

<img src="https://github.com/user-attachments/assets/c203ffa9-499c-4d8c-a99b-23965bba292e" width="300px">

When the button is disabled (when the map is zoomed too far out), the grey overlay and transparency styling should remain as now.

**Comment by marceloams** [comment]
Hi @ezwelty, could you please assign this issue to me? I'd like to contribute and work on it.
