### ISSUE TITLE
Adding a location with a review shows the location without the review

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#513]
A user can optionally submit a first review when adding a location. However, only the location is then displayed, and a page refresh or reselecting the location is needed for the review to also appear. This seems like an easy thing to fix in theory because the response from `POST /locations` (from which the new location is rendered) also includes the newly-added review.

**Comment by paskal98** [comment]
Hi, i will be glad to take this issue

**Comment by ezwelty** [comment]
@paskal98 Welcome and thanks! I've assigned you the issue.
