### ISSUE TITLE
Make gap size between Sign In and Sign Up buttons not depend on the language

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#533]
A bit too close in French, and maybe slightly too far in English:

![Screenshot from 2024-10-21 10-56-22](https://github.com/user-attachments/assets/9fca349f-aac7-4dfe-aed0-8640c5fbecf2)
![Screenshot from 2024-10-21 10-57-34](https://github.com/user-attachments/assets/2058b79d-17ec-4431-831d-9e9390caabb1)

I like the gap size between the review and report buttons, can we have that regardless of the language setting?

**Comment by ahmedhalac** [comment]
Hi @wbazant / @ezwelty. Is this still open? Can i fix it?
