### ISSUE TITLE
After adding a photo, the submit button slides down

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#556]
The review form on desktop is under the location page, so it usually needs to be scrolled down to. The photo upload and submit button are at the bottom, and reachable after the user has scrolled to them. Then uploading the photo grows the element, resulting in this:
![Screenshot from 2024-11-01 10-35-48](https://github.com/user-attachments/assets/745d8fef-b084-486a-9b00-44e788614982)

The submit button is temporarily lost, producing confusion and a small amount of annoyance.

**Comment by ahmedhalac** [comment]
Hi @wbazant. Can I try to fix this?

**Comment by wbazant** [comment]
Please do, thanks! Could I also recruit you as a reviewer for #555? If you check out that branch, see if my fix does what it says and if you can spot any related problems, and if you say it's all good I'll merge it in - and then you can base your solution on top of the updated main branch.

**Comment by ahmedhalac** [comment]
Hi @wbazant. Just a quick question. What is the best approach here? To set submit button fixed position or? Can you help me with the best solution? As I see it will be always pushed down by uploaded photo.

**Comment by wbazant** [comment]
Could it work to get a ref to the parent element which has the scrollbar, make a callback to scroll down to the bottom and pass it to the photo uploader, and trigger the callback after a photo is uploaded?
