### ISSUE TITLE
Unable to attach an image to a item when creating, or to a rating

### ISSUE THREAD

**Issue by taitems** [falling-fruit/falling-fruit-web#576]
While creating the listing referenced in the other issues, my goal was to attach an image. Once I converted the HEIC to a JPG using an online tool. It showed an error toast said it couldn't save the location data on my listing. 

Interestingly, it did create the listing, but it was only apparent it did upon refresh of the page.

It failed to attach the image, which makes me think the issue was instead something to do with the image itself. Was the file too large? Was there an error in its encoding? Did something bad happen server side?

The error was vague (failed to save the listing) and also incorrect (because it did save!).

> **UX Tenet:** Concisely and precisely describe the issue. Generic messages such as An error occurred lack context.

**Comment by wbazant** [comment]
Thanks for the report - I think I saw this too when adding locations with pictures when out with a phone. I wanted to make a photo of a tree swing and add it as a location, and the location was added but not the photo. I blamed bad connection and added error messages to errors in #567 but maybe it's about photo upload not being robust, maybe @ezwelty will be able to see in the logs what actually went wrong?

**Comment by ezwelty** [comment]
@taitems I'm hoping that your troubles were due to a bug in the API (now fixed) that rejected reviews with only photos. Could you test again and let me know what you find?

See https://github.com/falling-fruit/falling-fruit-api/commit/a1af1048342ba3fca6ea61901b499b34720bfc33

**Comment by ezwelty** [comment]
Closing as fixed based on report from @taitems.
