### ISSUE TITLE
Can't see a very zoomed-out map

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#593]
Go to a default view, and then zoom out with console open, getting to somewhere like
https://beta.fallingfruit.org/map/@41.1795296,-104.6203941,2z

![Screenshot from 2024-11-14 15-57-26](https://github.com/user-attachments/assets/e5f20e08-227a-4468-8df6-634a38962ecf)

The error says "Bounds not in the format {swlat},{swlng}|{nelat},{nelng}" for a URL like

```
https://beta.fallingfruit.org/api/0.3/types/counts?api_key=AKDJGHSD&muni=true&invasive=false&zoom=3&bounds=-75.8663615217419,129.69601217499996|87.07472492250575,21.063199674999993
```

which is not a good error message - the format is the same as something for a good map, e.g. 
```
https://beta.fallingfruit.org/api/0.3/types/counts?api_key=AKDJGHSD&muni=true&invasive=false&zoom=7&bounds=58.88480158542384,-148.6110548972271|68.00964305456506,-132.9006056784771
```

**Comment by ezwelty** [comment]
@wbazant Ah this is my fault on the API side. In my zeal to resolve https://github.com/falling-fruit/falling-fruit-api/issues/43, I required `swlng` < `nelng`, but of course this isn't the case if the bounds cross 180 degrees longitude. I dropped this requirement and clarified in the API docs:

> `swlat` must be less than `nelat`, but `swlng` can be larger than `nelng` if the box crosses the line of 180 degrees longitude.

Should now be fixed.
