### ISSUE TITLE
Bearer token sent in Authorization header even if signed out

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#599]
The website seems to naively include an Authorization header with a bearer token (presumably if it finds one in local storage) to calls to the API even if no user is currently signed in. This results in all sorts of problems, including that the API may falsely attribute actions to a user, or respond with unauthorized errors ("Token is invalid") if the token is expired.

One of the stranger results comes when trying to log in and an invalid token error is returned because the API call to /user has an invalid token. For some reason, checking "Remember me" bypasses this issue). Signing in and back out then seems to fix the issue.

**Comment by wbazant** [comment]
I'm having a go at this, as you say, `src/utils/api.ts` doesn't check redux and just checks if the token is in or not.

To reproduce, one can log out, then do this in the console:
```
localStorage.setItem('authToken', 'incorrect test token') 
```
and attempt to upload a photo. The photo upload should succeed - right now it doesn't because the token gets rejected.
