### ISSUE TITLE
Remove round borders from location drawer photo

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#602]
Note how the round borders leave a strange gap with the top of the window when the drawer is fully opened:

<img src="https://github.com/user-attachments/assets/b55539f1-2bcc-40f6-ad16-7cc68569f754" width="300px">

**Comment by thecrusader25225** [comment]
i can work on it

**Comment by thecrusader25225** [comment]
@wbazant I'm sorry I couldn't set it up locally and since I'm a beginner, I gave up on it. However if I could run it locally I think there is a probability that I'd be able to fix the problem

**Comment by christiancordeiro** [comment]
I took the liberty of resolving this and opening a PR, I hope nothing is wrong.

**Comment by thecrusader25225** [comment]
@wbazant since its closed, then I guess I've no business here?

**Comment by wbazant** [comment]
@thecrusader25225 hm, the issue got solved, but there's plenty more to do on the project if you'd like to contribute!

If you've learned to run a site locally and can see changes you're making, then you're in good shape to look for another small thing to try fix.
