### ISSUE TITLE
Replace Twitter bird with X logo on /sharing page

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#607]
The link to our X page was updated (https://github.com/falling-fruit/falling-fruit-web/issues/495), but I just realized that the same needs to be done on the sharing page, where we still display the old Twitter logo when linking to other organizations:
https://beta.fallingfruit.org/sharing

@ahmedhalac Interested 😉  ?

**Comment by ahmedhalac** [comment]
@ezwelty sure. Will take this one.
