### ISSUE TITLE
Editing location form broken

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#630]
The error is:
```
Property 'lat' doesn't exist.
```

Seems to consistently happen, both main branch and what's deployed to beta.fallingfruit.org.

**Comment by ezwelty** [comment]
Yikes, how did that bug slip in?! The error from the API isn't surprising, because the PUT request to /locations/:id issued by the website is complete empty/absent.

**Comment by wbazant** [comment]
It was a slippery one, of my authorship! I've merged in the fix to get the commit on a local branch.
